# -*- coding: utf-8 -*-
"""
/***************************************************************************
 AnalisiDusaf7ComuneLombardoPlugin
                                 A QGIS plugin
 Analisi DUSAF 7 per Comuni lombardi con QC-4
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-09
        copyright            : (C) 2026 by Marco Stefano La Sala
        email                : marco.lasala85@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software: you can redistribute it and/or modify  *
 *   it under the terms of the GNU Affero General Public License as        *
 *   published by the Free Software Foundation, either version 3 of the    *
 *   License, or (at your option) any later version.                       *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Marco Stefano La Sala'
__date__ = '2026-05-09'
__copyright__ = '(C) 2026 by Marco Stefano La Sala'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load AnalisiDusaf7ComuneLombardoPlugin class from file AnalisiDusaf7ComuneLombardoPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .analisi_dusaf7_comune_lombardo import AnalisiDusaf7ComuneLombardoPluginPlugin
    return AnalisiDusaf7ComuneLombardoPluginPlugin(iface)
