# -*- coding: utf-8 -*-

"""
/***************************************************************************
 AnalisiDusaf7ComuneLombardoPlugin
                                 A QGIS plugin
 Analisi DUSAF 7 per Comuni lombardi con QC-4
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-05-09
        copyright            : (C) 2026 by Marco Stefano La Sala
        email                : marco.lasala85@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software: you can redistribute it and/or modify  *
 *   it under the terms of the GNU Affero General Public License as        *
 *   published by the Free Software Foundation, either version 3 of the    *
 *   License, or (at your option) any later version.                       *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'Marco Stefano La Sala'
__date__ = '2026-05-09'
__copyright__ = '(C) 2026 by Marco Stefano La Sala'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

import os
import sys
import inspect

from qgis.PyQt.QtWidgets import QAction
from qgis.PyQt.QtGui import QIcon

from qgis.core import QgsApplication
from .analisi_dusaf7_comune_lombardo_provider import AnalisiDusaf7ComuneLombardoPluginProvider

cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]

if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)


class AnalisiDusaf7ComuneLombardoPluginPlugin(object):

    def __init__(self, iface):
        self.iface = iface
        self.provider = None
        self.action = None
        self._dialog = None

    def initProcessing(self):
        """Init Processing provider for QGIS >= 3.8."""
        self.provider = AnalisiDusaf7ComuneLombardoPluginProvider()
        QgsApplication.processingRegistry().addProvider(self.provider)

    def open_algorithm_dialog(self):
        """Apre il dialog principale del plugin.

        Sostituisce il vecchio form Processing aperto direttamente: l'algoritmo
        rimane disponibile in Processing Toolbox per modelli e script.
        """
        from .ui import DusafMainDialog

        # Reusing the same instance keeps the log and the cached comuni list
        # populated across reopen events; the user can run the workflow many
        # times without re-fetching the autocomplete.
        if self._dialog is None:
            self._dialog = DusafMainDialog(self.iface)

        self._dialog.show()
        self._dialog.raise_()
        self._dialog.activateWindow()
    
    def initGui(self):
        self.initProcessing()

        icon_path = os.path.join(os.path.dirname(__file__), "icon.png")

        if os.path.exists(icon_path):
            icon = QIcon(icon_path)
        else:
            icon = QIcon()

        self.action = QAction(
            icon,
            "Analisi DUSAF 7 - Comune Lombardo",
            self.iface.mainWindow()
        )
        self.action.setObjectName("analisi_dusaf7_comune_lombardo_action")
        self.action.setToolTip("Avvia Analisi DUSAF 7 per Comune lombardo")
        self.action.triggered.connect(self.open_algorithm_dialog)

        self.iface.addToolBarIcon(self.action)
        self.iface.addPluginToMenu("Analisi DUSAF 7", self.action)

    def unload(self):
        if self._dialog is not None:
            try:
                self._dialog.close()
                self._dialog.deleteLater()
            except Exception:
                pass
            self._dialog = None

        if self.action is not None:
            self.iface.removeToolBarIcon(self.action)
            self.iface.removePluginMenu("Analisi DUSAF 7", self.action)
            self.action = None

        if self.provider is not None:
            QgsApplication.processingRegistry().removeProvider(self.provider)
            self.provider = None